name: allure-report
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - testing

jobs:
    generate-report:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 16
                
            - name: Download Cypress
              uses: bahmutov/npm-install@v1
              env:
                  CYPRESS_INSTALL_BINARY: 0

            - name: Check Cypress cache
              run: |
                  npx cypress cache path
                  npx cypress cache list
            - name: restore / cache the binary
              id: cache-cypress
              uses: actions/cache@v3
              with:
                  path: ~/.cache/Cypress
                  key: >-
                      cypress-cache-v2-${{ runner.os }}-${{ hashFiles('**/package.json')
                      }}
            - name: Install Cypress
              run: |
                  npx cypress install
                  npx cypress cache list
            - name: Run Cypress
              continue-on-error: true
              run: npx cypress run --spec "e2e/3-GA/*.spec.js" --env allure=true --browser chrome
              # env:
              #     CYPRESS_SPLIT_SPEC_API_KEY: '${{ secrets.SPLIT_SPEC_API_KEY }}'

            - name: Get Allure history
              uses: actions/checkout@v3
              if: always()
              continue-on-error: true
              with:
                  ref: allure
                  path: allure

            - name: Generate Allure Report
              uses: simple-elf/allure-report-action@master
              if: always()
              with:
                  allure_results: allure-results
                  gh_pages: gh-pages

            - name: Deploy report to Github Pages
              if: always()
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: allure-history

            - name: Notify dedicated teams channel
              uses: jdcargile/ms-teams-notification@v1.3
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }} 
                ms-teams-webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
                notification-summary: "https://jhinzzz.github.io/Cypress-test/"
                notification-color: 17a2b8
                timezone: Asia/Shanghai